[package]
name = "whitespacers"
version = "0.0.1"
authors = [ "CensoredUsername cens.username@gmail.com" ]

[dependencies]
itertools = "0.4.*"
crossbeam = "0.2.*"

[dependencies.dynasmrt]
path = "../../dynasm-rs/runtime"

[dependencies.dynasm]
path = "../../dynasm-rs/plugin"

[profile.release]
debug = true
lto = true
